exports.run = async (bot,message,args, prefix2) => {
		try{
      	const firebase = require("firebase")
      const database = firebase.database();
const Discord = require("discord.js")
let meta_server = "[..........]"
let meta_user = "[..........]"
let guilds = bot.guilds.cache.size
let users = bot.users.cache.size
if(guilds > 10) meta_server = "[█.........]"
if(guilds > 20) meta_server = "[██........]"
if(guilds > 30) meta_server = "[███.......]"
if(guilds > 40) meta_server = "[████......]"
if(guilds > 50) meta_server = "[█████.....]"
if(guilds > 60) meta_server = "[██████....]"
if(guilds > 70) meta_server = "[███████...]"
if(guilds > 80) meta_server = "[████████..]"
if(guilds > 90) meta_server = "[█████████.]"
if(guilds > 100) meta_server ="[██████████]"
       meta_user1 = "0%"
      if(users === 1000) meta_user1 = "1%"
if(users > 1000) meta_user1 = "1%"
      if(users === 5000) meta_user1 = "5%"
if(users > 5000) meta_user1 = "5%"
      if(users === 10000) meta_user1 = "10%"
if(users > 10000) meta_user1 = "10%"
      if(users === 15000) meta_user1 = "15%"
if(users > 15000) meta_user1 = "15%"
      if(users === 20000) meta_user1 = "20%"
if(users > 20000) meta_user1 = "20%"
      if(users === 25000) meta_user1 = "25%"
if(users > 25000) meta_user1 = "25%"
      if(users === 30000) meta_user1 = "30%"
if(users > 30000) meta_user1 = "30%"
      if(users === 35000) meta_user1 = "35%"
if(users > 35000) meta_user1 = "35%"
      if(users === 40000) meta_user1 = "40%"
if(users > 40000) meta_user1 = "40%"
      if(users === 45000) meta_user1 = "45%"
if(users > 45000) meta_user1 = "45%"
      if(users === 50000) meta_user1 = "50%"
if(users > 50000) meta_user1 = "50%"
      if(users === 55000) meta_user1 = "55%"
if(users > 55000) meta_user1 = "55%"
      if(users === 60000) meta_user1 = "60%"
if(users > 60000) meta_user1 = "60%"
      if(users === 65000) meta_user1 = "65%"
if(users > 65000) meta_user1 = "65%"
      if(users === 70000) meta_user1 = "70%"
if(users > 70000) meta_user1 = "70%"
      if(users === 75000) meta_user1 = "75%"
if(users > 75000) meta_user1 = "75%"
      if(users === 80000) meta_user1 = "80%"
if(users > 80000) meta_user1 = "80%"
      if(users === 85000) meta_user1 = "85%"
if(users > 85000) meta_user1 = "85%"
      if(users === 90000) meta_user1 = "90%"
if(users > 90000) meta_user1 = "90%"
      if(users === 95000) meta_user1 = "95%"
if(users > 95000) meta_user1 = "95%"
      if(users === 100000) meta_user1 = "100%"
if(users > 100000) meta_user1 = "100%"
       meta_server1 = "0%"
      if(guilds === 10) meta_server1 = "10%"
if(guilds > 10) meta_server1 = "10%"
      if(guilds === 15) meta_server1 = "15%"
if(guilds > 15) meta_server1 = "15%"
      if(guilds === 20) meta_server1 = "20%"
if(guilds > 20) meta_server1 = "20%"
      if(guilds === 25) meta_server1 = "25%"
if(guilds > 25) meta_server1 = "25%"
      if(guilds === 30) meta_server1 = "30%"
if(guilds > 30) meta_server1 = "30%"
      if(guilds === 35) meta_server1 = "35%"
if(guilds > 35) meta_server1 = "35%"
      if(guilds === 40) meta_server1 = "40%"
if(guilds > 40) meta_server1 = "40%"
      if(guilds === 45) meta_server1 = "45%"
if(guilds > 45) meta_server1 = "45%"
      if(guilds === 50) meta_server1 = "50%"
if(guilds > 50) meta_server1 = "50%"
      if(guilds === 55) meta_server1 = "55%"
if(guilds > 55) meta_server1 = "55%"
      if(guilds === 60) meta_server1 = "60%"
if(guilds > 60) meta_server1 = "60%"
      if(guilds === 65) meta_server1 = "65%"
if(guilds > 65) meta_server1 = "65%"
      if(guilds === 70) meta_server1 = "70%"
if(guilds > 70) meta_server1 = "70%"
      if(guilds === 75) meta_server1 = "75%"
if(guilds > 75) meta_server1 = "75%"
      if(guilds === 80) meta_server1 = "80%"
if(guilds > 80) meta_server1 = "80%"
      if(guilds === 85) meta_server1 = "85%"
if(guilds > 85) meta_server1 = "85%"
      if(guilds === 90) meta_server1 = "90%"
if(guilds > 90) meta_server1 = "90%"
      if(guilds === 95) meta_server1 = "95%"
if(guilds > 95) meta_server1 = "95%"
      if(guilds === 100) meta_server1 = "100%"
if(guilds > 100) meta_server1 ="100%"
if(users > 10000) meta_user = "[█.........]"
if(users > 20000) meta_user = "[██........]"
if(users > 30000) meta_user = "[███.......]"
if(users > 40000) meta_user = "[████......]"
if(users > 50000) meta_user = "[█████.....]"
if(users > 60000) meta_user = "[██████....]"
if(users > 70000) meta_user = "[███████...]"
if(users > 80000) meta_user = "[████████..]"
if(users > 90000) meta_user = "[█████████.]"
if(users > 100000) meta_user ="[██████████]"
verificado_user = "❌"
if(users > 100000) meta_user ="✅"
verificado_guild = "❌"
if(guilds > 100) meta_user ="✅"
let executedia2 = await database.ref("DuiConfig/ExecuteCmds").once('value')
    executedia = executedia2.val().exedia
   meta_cmddia = "[..........]"
    if(executedia > 10) meta_cmddia = "[█.........]"
    if(executedia > 20) meta_cmddia = "[██........]"
    if(executedia > 50) meta_cmddia = "[███.......]"
    if(executedia > 70) meta_cmddia = "[████......]"
    if(executedia > 90) meta_cmddia = "[█████.....]"
    if(executedia > 100) meta_cmddia = "[██████....]"
    if(executedia > 200) meta_cmddia = "[███████...]"
    if(executedia > 300) meta_cmddia = "[████████..]"
    if(executedia > 400) meta_cmddia = "[█████████.]"
    if(executedia > 500) meta_cmddia = "[██████████]"
    meta_cmddia1 = "0%"
      if(executedia === 2) meta_cmddia1 = "5%"
    if(executedia > 2) meta_cmddia1 = "5%"
      if(executedia === 5) meta_cmddia1 = "10%"
    if(executedia > 5) meta_cmddia1 = "10%"
      if(executedia === 10) meta_cmddia1 = "15%"
    if(executedia > 10) meta_cmddia1 = "15%"
      if(executedia === 15) meta_cmddia1 = "20%"
    if(executedia > 15) meta_cmddia1 = "20%"
      if(executedia === 20) meta_cmddia1 = "25%"
    if(executedia > 20) meta_cmddia1 = "25%"
      if(executedia === 25) meta_cmddia1 = "30%"
    if(executedia > 25) meta_cmddia1 = "30%"
      if(executedia === 30) meta_cmddia1 = "35%"
    if(executedia > 30) meta_cmddia1 = "35%"
      if(executedia === 35) meta_cmddia1 = "40%"
    if(executedia > 35) meta_cmddia1 = "40%"
      if(executedia === 40) meta_cmddia1 = "45%"
    if(executedia > 40) meta_cmddia1 = "45%"
      if(executedia === 45) meta_cmddia1 = "50%"
    if(executedia > 45) meta_cmddia1 = "50%"
      if(executedia === 50) meta_cmddia1 = "55%"
    if(executedia > 50) meta_cmddia1 = "55%"
      if(executedia === 60) meta_cmddia1 = "50%"
    if(executedia > 60) meta_cmddia1 = "60%"
      if(executedia === 70) meta_cmddia1 = "65%"
    if(executedia > 70) meta_cmddia1 = "65%"
      if(executedia === 80) meta_cmddia1 = "70%"
    if(executedia > 80) meta_cmddia1 = "70%"
      if(executedia === 90) meta_cmddia1 = "75%"
    if(executedia > 90) meta_cmddia1 = "75%"
      if(executedia === 100) meta_cmddia1 = "80%"
    if(executedia > 100) meta_cmddia1 = "80%"
      if(executedia === 200) meta_cmddia1 = "85%"
    if(executedia > 200) meta_cmddia1 = "85%"
      if(executedia === 300) meta_cmddia1 = "90%"
    if(executedia > 300) meta_cmddia1 = "90%"
      if(executedia === 400) meta_cmddia1 = "95%"
    if(executedia > 400) meta_cmddia1 = "95%"
      if(executedia === 500) meta_cmddia1 = "100%"
    if(executedia > 500) meta_cmddia1 = "100%"
          cmdexecutedia30 = 500
metaatig_cmdedia = "❌"
if(executedia > cmdexecutedia30) metaatig_cmdedia = "✅"
embed = new Discord.MessageEmbed()
.setTimestamp()
.setColor("BLUE")
.setTitle("**Metas a serem compridas:**")
.setDescription("> Essas são as meta do `Duizin`! legal né? Que tal ajudar a bate-lás, isto seria muito legal!")
.addField("**Servidores**", "**`"+meta_server1+"` `"+meta_server+"` - `"+(guilds.toLocaleString())+"/100` [`"+verificado_guild+"`].**")
.addField("**Usuarios**", "**`"+meta_user1+"` `"+meta_user+"` - `"+(users.toLocaleString())+"/100,000` [`"+verificado_user+"`].**")
.addField("**Comandos Executados por Dia**", "**`"+meta_cmddia1+"` `"+meta_cmddia+"` - `"+executedia.toLocaleString()+"/"+cmdexecutedia30+"` [`"+metaatig_cmdedia+"`].**")
.setThumbnail(bot.user.avatarURL())
message.quote("<@"+message.author+">", embed)
	} catch (err) {
				let messageArray = message.content.split(" ");
    let command = messageArray[0];
      const Discord = require("discord.js")
	error = new Discord.MessageEmbed()
.setColor("RED")
.setTimestamp()
.setTitle("**Falha ao Executar o Comando.**")
.setDescription("> **O comando `"+(prefix2+command.slice(prefix2.length))+"` deu erro interno!** \n \n **Querendo denunciar o erro? Entre no meu [Servidor de Suporte](https://discord.gg/w6uZyBu) e denuncie no chat `#bugs`, se possível com prints!** \n\n```js\n"+err+"\n```")
message.quote("<@"+message.author+">", error)
}
}
exports.help = {
	name: "meta",
	aliases:[]
}